version: "2"
services:
  ldap:
    image: edtasixm06/ldapserver19:latest
    container_name: ldapserver
    hostname: ldapserver
    ports: 
      - "389:389"
    networks:
     - mynet
  ssh:
    image: edtasixm06/ssh19:base
    container_name: ssh
    hostname: ssh
    volumes:
      - "homes:/tmp/home"
    ports:
            - "2022:22"
    privileged: true
    networks:
     - mynet
networks:
  mynet:
volumes:
  homes:

